global class CrearOCWrapper {

	global class XA {
		public String value;
		public String apiName;
	}

	public String idPlan;
	public String idCuenta;
	public String idContactoAdministrativo;
	public String idContactoTecnico;
	public String idSucursal;
	public Double valorTotal;
	public String descripcionOrden;
	public Integer duracionMes;
    public Integer cantidad;
	public String resultadoOperacion;
    public String codigoRespuesta;
	public List<XA> XAs;
	
}